<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSearch</name>
   <tag></tag>
   <elementGuidId>8ed5a7ad-3308-4074-a1a9-33fc447f7126</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucSearch_btnSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucSearch_btnSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;SEARCH&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0685086-8e86-4cad-a7e1-a4e8577fe08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6d8af809-74e2-4d68-9e73-eb0e2532a285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucSearch$btnSearch</value>
      <webElementGuid>c0198c50-2ebf-4fe1-a62d-b43fbc6f1046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>52205d67-8c29-4d52-b4f2-1788d2fa8483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucSearch$btnSearch&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>edd374f0-9953-4d2c-8ffc-a9e6a8dbe886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucSearch_btnSearch</value>
      <webElementGuid>56cc2b76-00ef-4f4c-9eb0-9069c08e92a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>2b3fddac-d297-4ecc-b4c6-8288fa040c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucSearch_btnSearch&quot;)</value>
      <webElementGuid>5230bc22-ab8a-41ea-86eb-511f5fe787ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit Approval/iframe_Welcome, Sugeng, Head Office, Credit Analyst_mainPage</value>
      <webElementGuid>9bbc3bd1-5e72-49eb-9354-96aef4b6f0fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucSearch_btnSearch']</value>
      <webElementGuid>8a9cc220-b070-4472-a20c-5f9c273743b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucSearch_upButton']/input</value>
      <webElementGuid>a86c33b8-89dd-4a00-b215-43f09736277e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/input</value>
      <webElementGuid>7f9ffbfc-e37a-4988-adc0-0d6655cc8424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ucSearch$btnSearch' and @id = 'ucSearch_btnSearch']</value>
      <webElementGuid>bfe4a3df-4225-4272-ac62-08e986f84d75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
