<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ReturnNotes</name>
   <tag></tag>
   <elementGuidId>fdb5be16-8f26-4bfd-a4ea-82cb303c7f7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtReturnNotes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtReturnNotes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#txtReturnNotes</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>13449f02-4eae-47f4-8012-1369a9c8a908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtReturnNotes</value>
      <webElementGuid>180ce72b-4139-49f6-8c6c-420072c0a284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>078163d9-1005-46b2-8da8-f92b911aedc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>761d49ac-5bd3-4c52-aeef-5edc6bc804ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtReturnNotes</value>
      <webElementGuid>57bb9e48-6e05-452b-af21-395ddea77a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtReturnNotes&quot;)</value>
      <webElementGuid>a4942bad-7433-4bb3-9eec-06bbe160e8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit Approval/iframe_Welcome, Sugeng, Head Office, Credit Analyst_mainPage</value>
      <webElementGuid>24bf2a81-7e39-4477-b2da-d85ec008ef6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtReturnNotes']</value>
      <webElementGuid>9b789ae2-3c4e-4e81-b665-cae20f41dd67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dRHInfo']/table/tbody/tr[2]/td[2]/textarea</value>
      <webElementGuid>7524ead9-dc2e-4d5b-bb3b-785054f64506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[2]/textarea</value>
      <webElementGuid>29b50ed5-b748-47b1-b3ce-532d4e74b715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'txtReturnNotes' and @id = 'txtReturnNotes']</value>
      <webElementGuid>99e6b122-c0fe-45dc-ada4-a9704bfb1091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
