<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Span Posistion</name>
   <tag></tag>
   <elementGuidId>06fb9ba2-69fb-4025-85f1-3670568e2b13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='uModDRole_ctl00_gvRoles_lblJobTitleName_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uModDRole_ctl00_gvRoles_lblJobTitleName_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#uModDRole_ctl00_gvRoles_lblJobTitleName_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e422b9a3-a434-4984-b162-c6b144587ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uModDRole_ctl00_gvRoles_lblJobTitleName_0</value>
      <webElementGuid>87edeba6-423c-4bfb-8038-b531429ddfb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADMIN CREDIT</value>
      <webElementGuid>f0fd24d0-9e41-4b85-9acc-03a479e12bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uModDRole_ctl00_gvRoles_lblJobTitleName_0&quot;)</value>
      <webElementGuid>59d2e7bc-ecfa-4c90-9fbd-aacdb3bc9823</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='uModDRole_ctl00_gvRoles_lblJobTitleName_0']</value>
      <webElementGuid>e5ad8e8b-9431-4c64-a2fe-8dac1e2877fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='uModDRole_ctl00_gvRoles']/tbody/tr[2]/td[2]/span</value>
      <webElementGuid>88749aeb-8101-4798-96d0-b6087e2e6c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KEDOYA'])[1]/following::span[1]</value>
      <webElementGuid>e79b31ba-88b7-4d39-95ba-f3d4729c6af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::span[2]</value>
      <webElementGuid>3ad84ce5-8c68-4a14-aa73-77998bda3d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Admin'])[1]/preceding::span[1]</value>
      <webElementGuid>7bffccb8-cea1-4bcb-8255-bbce18eabd40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[1]/preceding::span[2]</value>
      <webElementGuid>50484f2f-f1ba-41d9-86ca-4a099c0fbfc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADMIN CREDIT']/parent::*</value>
      <webElementGuid>d98b67bd-7f55-4e27-9bc6-e1c67074b593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>833213bd-95f2-44c5-a8ab-fc22d22d219a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'uModDRole_ctl00_gvRoles_lblJobTitleName_0' and (text() = 'ADMIN CREDIT' or . = 'ADMIN CREDIT')]</value>
      <webElementGuid>284814ab-8aa7-4d36-b9db-bb6abf3288f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
