<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span Office</name>
   <tag></tag>
   <elementGuidId>1b286fa9-fa86-4c87-af3c-1062c2e43834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='uModDRole_ctl00_gvRoles_lblOfficeName_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uModDRole_ctl00_gvRoles_lblOfficeName_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;KEDOYA&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c7fa6bb8-02aa-4655-872d-a559e71a4216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uModDRole_ctl00_gvRoles_lblOfficeName_0</value>
      <webElementGuid>78ae4b4d-9f4f-4da4-97a8-d2e88f66e4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KEDOYA</value>
      <webElementGuid>7e46bff5-45f2-48fb-9514-73ccc608fba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uModDRole_ctl00_gvRoles_lblOfficeName_0&quot;)</value>
      <webElementGuid>6ddf301d-ffda-4ea0-9cba-6133d068b805</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='uModDRole_ctl00_gvRoles_lblOfficeName_0']</value>
      <webElementGuid>b71307eb-1e9a-4bcb-be0f-70a844b6547c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='uModDRole_ctl00_gvRoles']/tbody/tr[2]/td/span</value>
      <webElementGuid>5c9d1698-fdbd-40ad-94a7-1b21f8095440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::span[1]</value>
      <webElementGuid>cd970581-1bad-4231-835c-85f72cf3a933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROLE'])[1]/following::span[1]</value>
      <webElementGuid>738d138d-42ee-4024-bd09-9384527ee6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMIN CREDIT'])[1]/preceding::span[1]</value>
      <webElementGuid>78423fde-1776-4f03-80aa-23ea268cb3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Admin'])[1]/preceding::span[2]</value>
      <webElementGuid>f300d82c-b3be-4941-860c-d567ef49fc70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KEDOYA']/parent::*</value>
      <webElementGuid>e805b3d4-9efc-4219-8819-82031cd6d744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>ed8531b7-0a72-409a-ba64-27aa52c5f605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'uModDRole_ctl00_gvRoles_lblOfficeName_0' and (text() = 'KEDOYA' or . = 'KEDOYA')]</value>
      <webElementGuid>f337f867-8d9e-4eb4-9856-403083180231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
