<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</name>
   <tag></tag>
   <elementGuidId>12dd5ed2-5400-4b19-bb44-3b33a5039354</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainPage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;mainPage&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>dbbc5eb7-09db-4ba6-9601-1598ffcdca92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainPage</value>
      <webElementGuid>816e4c7a-ff43-4e7c-a29d-f8f3991173c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mainPage</value>
      <webElementGuid>7cae6eb7-c806-4522-b663-34f9e94ca766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>79f2f5a8-6980-460d-ba06-42847cc22919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>LOS.X/CreditProcess/CreditReview/CreditReviewPagingX.aspx</value>
      <webElementGuid>01bb1b26-fce8-469a-a9bc-21cd6b733e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainPage&quot;)</value>
      <webElementGuid>5cc08724-40de-4214-9c52-e3387c11f9ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainPage']</value>
      <webElementGuid>02902181-b7e6-4b32-9fc8-42beb1c97938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/iframe[3]</value>
      <webElementGuid>4eebebe8-3462-4c31-8063-f9833d2ea4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[3]</value>
      <webElementGuid>b64064ac-2e07-4227-bfc0-743d19509b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'mainPage' and @name = 'mainPage' and @src = 'LOS.X/CreditProcess/CreditReview/CreditReviewPagingX.aspx']</value>
      <webElementGuid>a8e52b24-9efb-4e04-b475-d4869e83daff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
