<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tab APPROVAL RECOMMENDATION</name>
   <tag></tag>
   <elementGuidId>ffc11df3-d9ac-4f68-ae99-88f073da350d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lb_Tab_ApvRecommendation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lb_Tab_ApvRecommendation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;APPROVAL RECOMMENDATION&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>050f534a-5662-4b27-8fb8-2ecc3888b619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lb_Tab_ApvRecommendation</value>
      <webElementGuid>7b478ddc-7969-4389-9e28-37972f0a565a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabDisabled</value>
      <webElementGuid>41366097-1793-4b45-8b0b-a19a1e9b79f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('lb_Tab_ApvRecommendation','')</value>
      <webElementGuid>5844db35-31ac-4428-a579-41161d1ec680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>APPROVAL RECOMMENDATION</value>
      <webElementGuid>021287c4-c52c-40bd-83ca-8af5acb7ec2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lb_Tab_ApvRecommendation&quot;)</value>
      <webElementGuid>549351ea-5b36-4e62-9bad-511f0753dd6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Credit Review/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>03589423-6041-4732-a820-5a6817816ed5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lb_Tab_ApvRecommendation']</value>
      <webElementGuid>0672219f-60df-460a-9903-8813a6d47210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dTab']/a[2]</value>
      <webElementGuid>47d5cddc-1854-46f0-bb88-631829e6cd42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'APPROVAL RECOMMENDATION')]</value>
      <webElementGuid>fd2859d0-2126-47a7-bdbf-849d8a3ff373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEVIATION'])[1]/following::a[1]</value>
      <webElementGuid>cea7a640-2f2b-48c6-8d7f-d1447d62732c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/following::a[2]</value>
      <webElementGuid>0b4154f0-0ee0-4f21-9d03-a83ff4bfaebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[-]'])[2]/preceding::a[1]</value>
      <webElementGuid>d9bf7f2b-1ec0-4bcf-a435-884b431b42db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Exposure Period Deviation'])[1]/preceding::a[2]</value>
      <webElementGuid>01440a61-9424-429e-bf7f-09a9846f3a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='APPROVAL RECOMMENDATION']/parent::*</value>
      <webElementGuid>6a6e2c05-f89c-4213-97f3-d8d65a154803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('lb_Tab_ApvRecommendation','')&quot;)]</value>
      <webElementGuid>0bc15f7a-9cb5-4b2c-9752-3bbdf331e092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a[2]</value>
      <webElementGuid>d47a6869-4adf-40c8-8a1f-cb8875368dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lb_Tab_ApvRecommendation' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;lb_Tab_ApvRecommendation&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'APPROVAL RECOMMENDATION' or . = 'APPROVAL RECOMMENDATION')]</value>
      <webElementGuid>ae2ad7b7-baa2-4668-be8a-c5ba4928267b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
