<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WEAKNESS</name>
   <tag></tag>
   <elementGuidId>0ea8fe38-8b07-41bb-9d54-5f22fde1a188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='rptApvRcmndtn_txtRcmndtnValue_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rptApvRcmndtn_txtRcmndtnValue_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#rptApvRcmndtn_txtRcmndtnValue_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a661e53b-ce17-480d-8bbf-be858475c413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rptApvRcmndtn$ctl01$txtRcmndtnValue</value>
      <webElementGuid>0fe71bee-2798-411b-9504-4482ed9c9413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c5959fd7-2f50-4c5f-b356-b6fe07b0f3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>7de93962-06b2-4e75-a7d4-cdb3c67a9871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rptApvRcmndtn_txtRcmndtnValue_1</value>
      <webElementGuid>22a51bbc-7424-4a55-be3b-2e177cf749f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtNotesStyle</value>
      <webElementGuid>1c02f9b4-21db-465b-89d0-aa1ee49156e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rptApvRcmndtn_txtRcmndtnValue_1&quot;)</value>
      <webElementGuid>6e1952f7-53bd-4551-877b-11c42299d8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Credit admin/Credit Review/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>3aeccc59-18cd-475a-ae88-6890a409bb4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='rptApvRcmndtn_txtRcmndtnValue_1']</value>
      <webElementGuid>476c34a8-b614-4fc2-a9dc-579e79bdc771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dSectionApvRcmndtn']/table/tbody/tr[2]/td[2]/textarea</value>
      <webElementGuid>6351d3ed-773d-49c9-a458-422484de2915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/textarea</value>
      <webElementGuid>00d4cae3-c7a1-43c5-8317-dcee604bd43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'rptApvRcmndtn$ctl01$txtRcmndtnValue' and @id = 'rptApvRcmndtn_txtRcmndtnValue_1']</value>
      <webElementGuid>b3ebc473-70e4-4b6b-bac4-955696b2916a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
